### ISSUE TITLE
CollabPress Dashboard Clean-up

### ISSUE THREAD

**Issue by ericandrewlewis** [WebDevStudios/CollabPress#1]
The CollabPress dashboard needs some love. 

Currently on a vanilla install, Project browsing and the calendar browser aren't showing up. Let's get them back in the mix to begin with.

**Comment by scottbasgaard** [comment]
Working on this now.

**Comment by scottbasgaard** [comment]
Fixed 3a2a7b634f4e32afc9b775003c17a053bc539ab7
