### ISSUE TITLE
Collabpress Template Help Needed

### ISSUE THREAD

**Issue by ghost** [WebDevStudios/CollabPress#102]
I was wondering if anyone could help me with collabpress' templates. I was trying to use them on the front end and it seems as if the query string is not passing the requested project to the template and im not sure how to fix it. You can take a look at it at http://bit.ly/1n3qMC8 and http://bit.ly/1cxSErH.

Any help would be greatly appreciated. 

Thanks a Million

**Comment by williamsba** [comment]
Please keep all support questions in the support forum here: https://wordpress.org/support/plugin/collabpress

We're actively working through and catching up on support posts now.
