### ISSUE TITLE
Spelling Mistake in CollabPress Template

### ISSUE THREAD

**Issue by zacharyhickson** [WebDevStudios/CollabPress#104]
Hi Guys, just wanted to let you know that I noticed a spelling mistake in 

```
includes\templates\collabpress\content-single-project-calendar.php
```

on line 11 it reads 'collabress':

``` php
<h3>&nbsp;»&nbsp;<?php _e( 'Calendar', 'collabress' ); ?></h3>
```

I presume it is meant to say 'collabpress':

``` php
<h3>&nbsp;»&nbsp;<?php _e( 'Calendar', 'collabpress' ); ?></h3>
```

Not sure if this is the right place to post this, but just noticed this today?

**Comment by ericandrewlewis** [comment]
@zacharyhickson thanks dog, wanna pull request that?

**Comment by zacharyhickson** [comment]
Sure, sorry I'm new to GitHub and didn't have time to Google it :)

Awesome plug-in btw!
