### ISSUE TITLE
Due dates are in American format

### ISSUE THREAD

**Issue by scottbasgaard** [WebDevStudios/CollabPress#14]
See: http://wordpress.org/support/topic/due-dates-are-in-american-format

**Comment by ericandrewlewis** [comment]
Since WordPress settings allow you to create any custom date format allowed in PHP, and jQuery datepicker allows only a subset of that, I suggest we have a custom setting in CollabPress to choose between two basic date formats, MM/DD/YYYY and DD/MM/YYYY.

**Comment by scottbasgaard** [comment]
+1 Eric. Let's just do that.

**Comment by ericandrewlewis** [comment]
I'm gonna move this to Future Release, anything that isn't functionally limiting to the new UI is on the backburner for now.

**Comment by boonebgorges** [comment]
See also #32

**Comment by ericandrewlewis** [comment]
This is going to be fixed in #32, closing this as duplicate.
