### ISSUE TITLE
"Overview" Metabox in dashboard cheesy translatable

### ISSUE THREAD

**Issue by krafit** [WebDevStudios/CollabPress#18]
While working on the German translation of CollabPress I discovered a problem in the way the _Overview_ Metabox generates the plural forms.    

(Project vs ProjectS, etc.)

The problem is, German (an many other languages) do not handle plural forms like this. 
The result is a cheesy result in the German translation.

A fix would be **awesome**!

![Bildschirmfoto 2013-01-08 um 22 44 56](https://f.cloud.github.com/assets/1038789/51834/2bfa6ea2-59e0-11e2-9cf9-3af1f5b27c97.png)

**Comment by ericandrewlewis** [comment]
Indeed. In b79f6e58556e83ed84b46bb3e76725e4d45322c3 I fixed the code to support these translations. Thanks!

**Comment by krafit** [comment]
awesome!
