### ISSUE TITLE
Comment Notifications

### ISSUE THREAD

**Issue by markrisch** [WebDevStudios/CollabPress#21]
Eric,  Thanks for the quick reply. Here it is...

When a comment is made on a task, an email is sent to the person assigned the task. If he is the one making the comment, then his communication is being missed by the person who assigned the task in the first place. In other words, the comment notification only goes one way. What if the assignee needs to ask a question or get clarification form the assignor?

I think the comment notification should go to both the assignor and the assignee at a minimum, or even better just go to the person who didn't make the comment.

Thanks again.

**Comment by williamsba** [comment]
We should update the cp_send_email() function to accept an array of user IDs to email

**Comment by ericandrewlewis** [comment]
In 23a76da77233b596e6b2947c9b58f8aafdc48721, send update email to anyone who has commented on a task, as well as the user assigned to the task.
