### ISSUE TITLE
.open and .closed selectors in frontend.js are too generous

### ISSUE THREAD

**Issue by boonebgorges** [WebDevStudios/CollabPress#23]
In frontend.js, the '.open' and '.closed' selectors are way too generous, and are causing problems with other items that have these classes. I've run out of time at the moment - can't fix it right this second, but I wanted to make a note of it so I don't forget.

**Comment by scottbasgaard** [comment]
What is that jQuery even for? Maybe we dont' even need it anymore…

I see the same code in admin.js. I'm 99.9% this is old code and we can remove it.

**Comment by scottbasgaard** [comment]
Closed 093b200a20c6121c47e89f8efa6c16974c10b65a

**Comment by scottbasgaard** [comment]
100% sure it wasn't needed. Found the old commits in beanstalk regarding this.
