### ISSUE TITLE
Verify multisite installation has no issues

### ISSUE THREAD

**Issue by ericandrewlewis** [WebDevStudios/CollabPress#3]
White screens were reported on a multisite installation.

**Comment by scottbasgaard** [comment]
@ericandrewlewis were you able to replicate this?

**Comment by ericandrewlewis** [comment]
I had no issues with it. Brad mentioned Otto got white-screened somewhere in the process, and guessed it could be blamed on multisite.

**Comment by scottbasgaard** [comment]
Closing. Let's revisit if issue arises again…
