### ISSUE TITLE
Feature Request: Search Projects and Tighter Group Integration

### ISSUE THREAD

**Issue by ac23** [WebDevStudios/CollabPress#31]
Hey guys,
First and foremost, the UI improvements for 1.3+ are looking very good. I had intended to stay away from CollabPress in favor of GTM which I felt was too powerful, but the plugin is now far too outdated and does not play well with 1.7, and I'm trying to future-proof this client project I am developing as best as possible. I was happy to see a lot of movement in CP development over the past few weeks while I've been playing around with GTM.

A couple feature requests:
- Frontend Project (and possible task) search: It would be extremely helpful and beneficial to allow users to search through all projects without needing to dig into a specific BP group and see what's available.
- Tighter group integration: As it currently stands, a tab is added to each group for projects and you can view projects / add a new task / or edit a project. But the functionality on group pages is limited in comparison to whatever page you drop the front-end shortcode in. I'd prefer to simply the flow and have everything available in the overall front-end CP dashboard be available on a per group level -- so picking users and assigning them to tasks, a calendar view, etc. Bouncing people from one area of the site to another for further project management seems redundant. (I could be missing something and maybe this is already possible, but I don't think so).

Thanks for your continued hard work.

**Comment by ericandrewlewis** [comment]
Front-end project search probably won't happen anytime soon in CP core. Although, now that CollabPress templates are fully customizable and overridable by your theme, you could easily add this functionality in to your site.

Tighter group integration is definitely a worthy upgrade - at least in feature parity like the calendar views and file uploads. Controlling membership in a CollabPress project within a BP group seems a bit redundant. I'm going to close this and create a new issue specifically for BP feature parity with CollabPress vanilla.
