### ISSUE TITLE
Fix BP integration

### ISSUE THREAD

**Issue by ericandrewlewis** [WebDevStudios/CollabPress#37]
Broke this in trunk tonight. Will fix this week.

**Comment by ericandrewlewis** [comment]
@boonebgorges - there's some discrepancy with the new CP UI and the BuddyPress projects loop layout. What are your thoughts? Should we use the new style, or use the paginated/sortable list?

**Comment by boonebgorges** [comment]
Hey Eric. If you can easily mod the group view using the new UI so that
only that specific group's projects are listed (and no other current
functionality is lost), I think it's fine to move to the new format.
People can always switch back with a custom BP template if they want.

**Comment by ericandrewlewis** [comment]
Fixed in a341d2e157d05a9d1355adcd50a91935b3081a3c and a couple other related commits. 

boonegorges commented

> (and no other current functionality is lost)

The lost functionality here is a devoted page for task lists (which can be brought back if someone wants to do the legwork, but for now the nested task lists and tasks page is quite workable), and the pagination / sortability on the projects Groups page, which we can bring back before release during beta if anyone wants to toss it back in.
