### ISSUE TITLE
Nesting task lists

### ISSUE THREAD

**Issue by Ardibee** [WebDevStudios/CollabPress#44]
Should I be able to nest task lists (i.e. make one task list the parent of another task list) so that tasks are four levels deep (project >task list>task list>task)?

If not then it might be worth disabling drag-and-drop of one task list onto another in the "tasks" view.

**Comment by ericandrewlewis** [comment]
Thanks for the report! We're planning on only having one task-list level for now, it's a bug in the drag-drop code. Tossing onto the 1.3 milestone.

**Comment by Ardibee** [comment]
Not sure if this is related to the nested task lists but every now and again my hierarchy of tasks and lists gets completely flattened so everything is level 1 again - tasks and lists.  Is this the code wigging out and starting again when it finds something out of place?

**Comment by ericandrewlewis** [comment]
It could be - let's see if it wigs after this issue gets fixed.

**Comment by ericandrewlewis** [comment]
Fixed in 9403ef23d2b3c1c5b74d8beb04ef2681d252a0e6.

**Comment by ericandrewlewis** [comment]
@Ardibee - if you still have the "wigging out" issue with task list sorting, please open up a fresh issue with as much detail you have.
