### ISSUE TITLE
CP dashboard error on WAMP / Desktop Server Pro

### ISSUE THREAD

**Issue by Ardibee** [WebDevStudios/CollabPress#45]
When trying to access the admin dashboard page CollabPress / CollabPress, I get the following error with the latest (RC1) version... Running W7 + Desktop Server Pro.  CollabPress / Settings works OK.  Front end (short-code) seems to run OK too.

Warning: require(C:\Users\Roger\Documents\CP-Single.dev\wp-content\plugins\CollabPress-master/includes/templates/collabpress/content-.php) [function.require]: failed to open stream: No such file or directory in C:\Users\Roger\Documents\CP-Single.dev\wp-content\plugins\CollabPress-master\includes\menus\dashboard.php on line 154

Fatal error: require() [function.require]: Failed opening required 'C:\Users\Roger\Documents\CP-Single.dev\wp-content\plugins\CollabPress-master/includes/templates/collabpress/content-.php' (include_path='.;c:\xampplite\php\PEAR') in C:\Users\Roger\Documents\CP-Single.dev\wp-content\plugins\CollabPress-master\includes\menus\dashboard.php on line 154

**Comment by ericandrewlewis** [comment]
In 14934c3c200128de2d58334d524b496c3bd218a2, use 'admin_init' for back-end bootstrapping, 'wp' for front-end
