### ISSUE TITLE
Can't open dashboard on rc1

### ISSUE THREAD

**Issue by pemaia** [WebDevStudios/CollabPress#47]
When I try to open dashboard I get this error:

Fatal error: require(): Failed opening required '/home/dialogos/public_html/prototipo/wp-content/plugins/CollabPress/includes/templates/collabpress/content-.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/dialogos/public_html/prototipo/wp-content/plugins/CollabPress/includes/menus/dashboard.php on line 154

**Comment by ericandrewlewis** [comment]
Yep, that was issue #45. It's been fixed in master.
