### ISSUE TITLE
CustomPress and CollabPress use the same PHP constants

### ISSUE THREAD

**Issue by ericandrewlewis** [WebDevStudios/CollabPress#60]
A few are in conflict( CP_VERSION, CP_PLUGIN_URL, CP_PLUGIN_DIR). 

Let's change all of ours to COLLABPRESS_*

**Comment by ericandrewlewis** [comment]
Fixed in 236deddc8e990df0cd5eab8e5808f9816fbffaed, 57c0bd6e4a90f68f81bcb55f405f40a8cea258db, and f60b0dddeae77eb4ace044cdf9b77f64b99a2bd0

**Comment by boonebgorges** [comment]
Awesome, this looks good
