### ISSUE TITLE
Error on New Project in IE

### ISSUE THREAD

**Issue by ericandrewlewis** [WebDevStudios/CollabPress#64]

**Comment by ericandrewlewis** [comment]
Reported [here](http://wordpress.org/support/topic/add-project-link-front-end-and-back-end-error-on-page)

**Comment by ericandrewlewis** [comment]
I can't reproduce in IE 8 or 9.

**Comment by mikeburns** [comment]
I don't get an error here, but in Chrome + FF nothing happens in the frontend (using the shortcode).

**Comment by ericandrewlewis** [comment]
Tested on XP + FF 19, XP + Chrome 25, XP + IE 8, XP + IE 9, Win7 + IE 8, Win7 + IE9. No issues creating new project. I'm closing this out, if anyone has specific versions where an error can be produced please share.
