### ISSUE TITLE
Change Project, Task List, Task Data Structure

### ISSUE THREAD

**Issue by scottbasgaard** [WebDevStudios/CollabPress#7]
Here is the current data structure hierarchy:

Project (CPT) > Task List (CPT) > Tasks (CPT)

The proposed data structure change would look like this:

Project (CPT) > Task List (Taxonomy/Optional) > Tasks (CPT)

PROS:

Tasks Lists would not be required.  Most CP users don’t need Tasks Lists, so this new structure would allow them the ability to create a Project and start creating tasks immediately.
Tasks Lists as a custom taxonomy would break the one-to-one relationship that currently exists and would allow a one-to-many relationship between tasks and task lists
Grouping tasks under a task list taxonomy would utilize the core grouping feature of WordPress taxonomies.

CONS:

Backwards compatibility would be a real pain.  An importer would need to be built to convert existing Task List CPT entries to custom taxonomy terms and all tasks attached to the old CPT would need to be attached to the new term

**Comment by Ardibee** [comment]
Another benefit of making task lists a custom taxonomy is that you could (potentially) nest task lists for larger, more complicated projects that were broken down into stages and sub-stages.  Combine that with template projects and it could be a very powerful feature.

**Comment by ericandrewlewis** [comment]
As of now, I've given tasks the ability to be assigned to projects themselves, and task lists allow for the same one-level deep organization as in pre-1.3. I'm wondering now if we should re-consider converting task lists to taxonomies, as this structure works pretty well.

**Comment by Ardibee** [comment]
That works for me as I'm holding fire on a project until 1.3 is ready, so now is as good a time as ever (I won't be trying to convert legacy data).  I imagine lots of your long-term users will need a migration path or tool to repatriate their old projects with the new plug-in.  The new front-end may be enough of a prize to get legacy users to adopt the new model - if you release 1.3 with the old structure and then offer 1.3.1 with the new taxonomy you may get more complaints than thank-you's... :-)

I think the taxonomy approach will also be useful when (or if?) you introduce template projects, as it may make it easier to compare similar stages (e.g. duration) across multiple projects.

**Comment by ericandrewlewis** [comment]
I'm gonna say this is closed, fixed, as it works fine with Task Lists as custom post types instead of taxonomies, and there's discussion that needs to happen about the implementation of task lists as taxonomy that hasn't happened, and probably won't before we beta 1.3. Re-open if there's any follow-up.

**Comment by boonebgorges** [comment]
>  I've given tasks the ability to be assigned to projects

I think this is fine. Certainly for 1.3. I think there are other advantages to moving to taxonomies aside from the ability to leave out task lists, but until I have a bunch of time to devote to writing the replacement and the migration, I will shut my big mouth :)

**Comment by Ardibee** [comment]
OK Eric, I understand why - it would be good to see v1.3 out there in the wild. This does present me with a bit of a dilemma though, as I'm going to need task lists to structure my projects... Should I wait for v1.4?

**Comment by ericandrewlewis** [comment]
@Ardibee task lists will still be available, the only difference in the general structure from 1.2 to 1.3 is that tasks can be assigned to projects without the need for task lists.

**Comment by Ardibee** [comment]
Thanks Eric.  I was worrying about migrating from CPT task lists to taxonomy-based lists later, when I have a site full of projects... I guess I'll cross that bridge when I come to it. :-)

BTW, are you still looking for feedback (on the trunk version) on make.collabpress.org (or here on GitHub, come to think of it)?  

Have a great Easter,
Roger.

**Comment by ericandrewlewis** [comment]
@Ardibee If we do switch over task lists in the future, we'll be sure to have an auto-import of old task list data into the new structure, so you shouldn't even notice ;)

Feedback would be appreciated on trunk, however as we close in on release (I want to have a beta out early next week), we'll be sticking to bug fixes only, unless someone takes over development of an approved feature. You can put your feedback as Github issues, or get in the IRC chatroom for CollabPress on the Freenode server, chatroom #collabpress. I'm lurking there on the regular.

**Comment by Ardibee** [comment]
Hi Eric, I have some feedback on the look-and feel... I'm compiling it in a Word document as it contains screen-shots and commentary.  Can I email it to you (and if so, at what address)?  Not sure I can attach a doc or pdf on here or on make.collabpress.org

**Comment by ericandrewlewis** [comment]
@Ardibee sure, feedback would be welcome, I'll take a look at it. You can email me at eric.andrew.lewis at gmail. Just be aware, unless someone steps up to make any changes that are approved in the next few days, they probably won't get in to 1.3, although we can have a quick follow-up release when some folks have time to devote.
