### ISSUE TITLE
Can't add HTML in project description

### ISSUE THREAD

**Issue by ericandrewlewis** [WebDevStudios/CollabPress#73]

**Comment by HeleneFi** [comment]
Very important indeed, bcause the project description is the project showcase! So eventually giving access to an editor for some advanced formating of the description area would be cool.

**Comment by ericandrewlewis** [comment]
Fixed in 4a0268cd163fd63a592b3998aa5e1d09c4b042ec

**Comment by HeleneFi** [comment]
Not sure how I can fix this myself. Is there long before the next upgrade?
