### ISSUE TITLE
Compatibility issues with Cbox 1.04 and/or BuddyPress 1.7

### ISSUE THREAD

**Issue by HeleneFi** [WebDevStudios/CollabPress#76]
Not sure if this is the right place to post this, but as these three are being developed it seems by the same team (in relation to Boone George) they would be expected to work together :)

So what doesn't work now with Cbox 1.04 integrating BP 1.7 (which was OK with Cbox 1.02 and prev version of BP) is I can't access existing projects or create new ones, and the submit button of create task has no outcome.

**Comment by boonebgorges** [comment]
You assume that the left part of my brain is in contact with the right. :-D

**Comment by HeleneFi** [comment]
I do :). And that's when great user experiences are created! :D

**Comment by HeleneFi** [comment]
Seems version 1.3.1.2 has fixed what I have reported. UE still needs a bit of optimizing, but we're getting there!
