### ISSUE TITLE
Undefined function cp_recent_activity() in Admin dashboard. Fresh WP install, fresh CP install.

### ISSUE THREAD

**Issue by deltafactory** [WebDevStudios/CollabPress#85]
I noticed it when I couldn't get the screen options to display:

Fatal error:  Call to undefined function  cp_recent_activity() in ...../wp-content/plugins/collabpress/includes/cp-core.php on line 59

**Comment by ericandrewlewis** [comment]
Fixed in 2ebfd6293149fb7c19d4edf1afc06a873fb48a4b
