### ISSUE TITLE
Duplicate Task and Task List - Collabpress 1.4

### ISSUE THREAD

**Issue by ruudvh** [WebDevStudios/CollabPress#86]
When creating a new task, a second identical task is created.
When creating a new task list, three other identical task lists are created.

Clean install of WordPress, with default theme and no other plugins.

**Comment by ericandrewlewis** [comment]
I can't reproduce. Did you click the submit button multiple times?

**Comment by ruudvh** [comment]
I was thinking the same thing, but I only click once.

**Comment by williamsba** [comment]
Just tested on master and I can't reproduce this.

**Comment by ruudvh** [comment]
I think I found the issue / solution. When removing Collabpress it leaves a table in the database, removing this and reinstalling it seems to have worked. Even though the table does not seem to be associated with tasks or task lists.

Also on a side note, it seems that when having installed both Collabpress and WP-Project-Manager the projects of Collabpress will return a 404.
