### ISSUE TITLE
Dashboard widgets cannot be moved once Collabpress is activated

### ISSUE THREAD

**Issue by novalore** [WebDevStudios/CollabPress#97]
That is the error in error.log (anonymized a bit):
FastCGI: server "/var/www/clients/client120/web132/cgi-bin/php5-fcgi-*-80-domain.tld" stderr: PHP message: PHP Fatal error:  Call to undefined function cp_recent_activity() in /var/www/clients/client120/web132/web/wp-content/plugins/collabpress/includes/cp-core.php on line 59, referer: http://domain.tld/wp-admin/admin.php?page=collabpress-dashboard&view=calendar

**Comment by ramiabraham** [comment]
Confirmed here as well; cp_recent_activity just needs an exists check.

**Comment by novalore** [comment]
Thanks for the quick fix.
